### ISSUE TITLE
Training with no relations in data

### ISSUE THREAD

**Issue by famube** [markus-eberts/spert#45]
I have a dataset without relation labels, but I would like to test your approach in spite of it (would you recommend?). However, an error occurs when training with no relation data, something related to 0-sized tensors. Have you also got this issue?

**Comment by markus-eberts** [comment]
I just trained a model on dataset without relations but did not get an error. Could you please send me the specific error message?

**Comment by markus-eberts** [comment]
On a second thought, you are probably getting an error if no relation types are specified in 'types.json', right? We did not handle this case since the model is build for joint entity and relation extraction. However, I think by adding a pseudo relation type to 'types.json' you should be able to run and train the model on entities only. It is, however, not optimal from an efficiency point of view (since relation related model parts are still run). You should get correct entity mention results regardless.

**Comment by famube** [comment]
I think there was something wrong with my data. I'm not getting this error anymore. Another issue (that I solved by limiting sentence sizes to about 250 tokens) seems to be related to vector sizes:

(venv) fmuniz@mummra:~/dmp/spert$ python spert.py predict --config configs/lener_predict_old.conf
--------------------------------------------------
Config:
{'prop_drop': '0.1', 'types_path': 'data/datasets/lener/types.json', 'max_pairs': '1000', 'max_span_size': '10', 'dataset_path': 'data/datasets/lener_old/test.json', 'model_path': 'data/models/lener', 'size_embedding': '25', 'eval_batch_size': '1', 'predictions_path': 'data/datasets/lener/predictions_old.json', 'tokenizer_path': 'bert-pt', 'sampling_processes': '4', 'model_type': 'spert', 'rel_filter_threshold': '0.4'}
Repeat 1 times
--------------------------------------------------
Iteration 0
--------------------------------------------------
Parse dataset 'dataset': 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 323/323 [00:02<00:00, 144.75it/s]
Predict:   3%|████                                                                                                                     | 11/323 [00:11<05:33,  1.07s/it]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/users/fmuniz/mp/spert/spert.py", line 39, in __predict
    input_reader_cls=input_reader.JsonPredictionInputReader)
  File "/data/users/fmuniz/mp/spert/spert/spert_trainer.py", line 148, in predict
    self._predict(model, dataset, input_reader)
  File "/data/users/fmuniz/mp/spert/spert/spert_trainer.py", line 280, in _predict
    inference=True)
  File "/data/users/fmuniz/mp/spert/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/users/fmuniz/mp/spert/spert/models.py", line 227, in forward
    return self._forward_inference(*args, **kwargs)
  File "/data/users/fmuniz/mp/spert/spert/models.py", line 90, in _forward_inference
    h = self.bert(input_ids=encodings, attention_mask=context_masks)[-2] #['last_hidden_state']
  File "/data/users/fmuniz/mp/spert/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/users/fmuniz/mp/spert/venv/lib/python3.5/site-packages/transformers/modeling_bert.py", line 783, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/data/users/fmuniz/mp/spert/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/users/fmuniz/mp/spert/venv/lib/python3.5/site-packages/transformers/modeling_bert.py", line 174, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/data/users/fmuniz/mp/spert/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/users/fmuniz/mp/spert/venv/lib/python3.5/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/data/users/fmuniz/mp/spert/venv/lib/python3.5/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 512 out of table with 511 rows. at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418

**Comment by markus-eberts** [comment]
This is due to BERT (the encoder used in SpERT) is restricted to a maximum of 512 tokens (you are getting the error since positional embeddings are only trained up to this size). However, since words are further split into sub-word units (by using sentencepiece) the sequence passed to BERT is usually longer than your original sequence. That's why restricting the sentences to a maximum of 250 is reasonable. This should also cover most real sentences I guess.

**Comment by famube** [comment]
Ok, thanks a lot.
